### ISSUE TITLE
Message to the consortium

### ISSUE THREAD

**Issue by martinheidegger** [dat-ecosystem/organization#2]
Private Message:

pmNhbGdsUlNBLU9BRVAtMjU2YWVkQVFBQmNleHT1Z2tleV9vcHOBZ2VuY3J5cHRja3R5Y1JTQWFueQKr
M3liY2NrNmlvZEpDclctQlEtdlNSSjhBTk9qV21ZMHdWUHdaaVRnRGhpeDllamgtM1ViQkZJc0xWUVY3
TTlqRjE3VHlBdUIxdEJJMFY4SGJnQlpreEhfYWtxd3RscVpQRFlEZWlodUNjSGVXTkk3YllHWHN4YTct
UFNXLXhRVG5RMlZ4UzJXcXRlN0Y2S0g0bC1Oc2RFYlVNbnZ5YWdSbmhoaE80a0N4cDBNTnlLMWxpRFNU
ZkJSS25pTG00WjI2ZmdxbGZWc0Z4QkN4M0o2SWlvcVFoeWhKRFA2RFJzWS04am5JdmhkYjB6dks0b0hx
eExYalF3dU9kSDB5S3NSRnNqU2t6U2R3UlNhdVJPTFF6V3Z5MElHVDRLeEI2YnZuOFIyaWlCQU9aTmZC
d1lQTUZKcnE3Qk1zakkxTFQzWFZjQXVlUzFWeFplZktLQXV5MjRwX0RLRGpja2I5RHh4alBFU3dDN0NX
TE0wSnBXVTVSY2xUZ1Y4Q1d5b3RtZ3hfWjRTVGZ0UHhNdG1QVjVzYnhZOEpYcW43TlU1b2t2d3VqYmV1
R3dXNWtleXpQei1UZkZGY0w5XzJrbThPc0ttVFdubi1nUk5uaGpnODRsdUEtYW1xdHk5elNlbmtGaGZC
Q25iZFlJSEwxLUxyOGFDNlU4VV9qVUIxOUlRRG42b2pldXBCT2lpZUlsMFZ5bWhxX0JtaVhLZUh6cHRx
UGtRRzJ6Rk5GdUhlNUtDOTc3WFowNmp1cGlRRlEzT2FDOXh3X3B4SF96YjlDZURLREptcUNOVEdpU3hG
ZlRKSTFCSXNyQjRDcVpORlBjX2hVaF9hZ1hDNHNFT2lIVFVBUGMzVDlYaFktdmlaUk9KWUs1ZkpLOUtP
bmNjWDNHeDBvNmUwTWlxcGsyUmwwa2vYQFkCAAtOsLw/PhR7cIABBVfcVPl9ao3X1Dbskh0Cb0RPyrf8
EmoncSFn/yBZ3fAXhXVqaJjyCdN/qG+/tdzaFCxhTb4mrLX9mWLAeqHdpBr5PUPREZSFQhkF65wrJqou
qwpM5jkfC5dkQaXlXYYXRKvgrtNtLH+aOlA5SCcCiX8IHvtLXP8AwJz2YcSpbEYYC9g8w2LtrRf6CL6F
s0Z20aR9ZAuy9lv3PMxhO23fyFsbqoUOZs0yrCn1C4UII5khiL+TdZn9ssADiV0Asr2g/fzgcVclR8Vo
ytH3MitK7JNu6PsLRejwZxFoaUsdqfvjD9RYmV0hTXLZXKfp2vwlZkxzjsfBv/BreRqeFSErJEfRwAgF
U6/pMK4ef/m2Q9V6U+C4e/lwYoWoBIcQ+C0Xi+U7OapSejNgmXKDtqDohlmMlrMVSKlPdBRbpT1yAldO
pQKRHzNKRSgue9xIWjDB/yS9ExjcHsjqr59WLv4QJ+jXt4HpsdtgALGVr6ayE+KUq+VSNvnqYPcuxufj
M2CcW/jdlzpYOufJ0cTFnlU+kxHWrJ9PV+T+zrhwtzQHDH6ESezt5KK6+4oRRqgkwykwn7FaAMfLgG1D
4NRl+XG+uzh04Mw3Gz/A6yQlvgtrrwcke/4sUn0jXpfoYedtrrSMhkApfAmMF3mSxAEVYD0OaYudfkkj
2EBZAgA25De6Jg2UqsdrPg3JPRvNPTlJJcwxrVw0eX7d3GzR3MDc8zj2EnElOABgenyTwtf3QXl/4B/N
xecbSh3k6ksfs2x42LU1EPxrE8zejiSNjVY7Zwg9wfKC5gc9XxfsoVlg62DLICMRWoNM3Lve2mzrLElz
eE3FXOohzLu9fi7Ip9ARmuIr0V+DXC2DD2SVOXOQ2cWl4ZiLOOzPeUXB6yHC5R0PQw/djE1BBqBv8Agp
gfsjrnsL3mQWApgoJjW6ltbdcnjiC9xI28CvhMyeA8WGqDtbz93y736ojcrJoeL7AephJzQnXPHeDyYp
cpIbZc+s90wGKTynJ7LAvzyhW3Waq7IlkMe6YMmo1mUS2yqEmTxMJUno4JBcSh8WfWoCLo7PWH4nMj6D
nUNa82z+xs+yCdjCuDEMe1jmLs04fKjv7hiwNIOEu9b9r2Dnhv4qDoMGt4fgdm1hunwd4dlse7qJPrKw
mEsxfIH1HUiaIDbHuR8+H8mwErGdrOo2jqg4btx/i9m6AjxsojRokWWoSEij1fH+EpVToITUeTvqV6Fe
cahEJicIx9nx4og1ePD1FN58VedgnSm6oalj+QT6IIyQZlReCW1uhSu3SlpzVyyMqSMZcODMM/kcgZu3
BBmPSzzB5ulWpsVIwoG2kW19m5JTWVy6Iib5BDc91nimJL59yg==

**Comment by martinheidegger** [comment]
pmNhbGdsUlNBLU9BRVAtMjU2YWVkQVFBQmNleHT1Z2tleV9vcHOBZ2VuY3J5cHRja3R5Y1JTQWFueQKr
M3liY2NrNmlvZEpDclctQlEtdlNSSjhBTk9qV21ZMHdWUHdaaVRnRGhpeDllamgtM1ViQkZJc0xWUVY3
TTlqRjE3VHlBdUIxdEJJMFY4SGJnQlpreEhfYWtxd3RscVpQRFlEZWlodUNjSGVXTkk3YllHWHN4YTct
UFNXLXhRVG5RMlZ4UzJXcXRlN0Y2S0g0bC1Oc2RFYlVNbnZ5YWdSbmhoaE80a0N4cDBNTnlLMWxpRFNU
ZkJSS25pTG00WjI2ZmdxbGZWc0Z4QkN4M0o2SWlvcVFoeWhKRFA2RFJzWS04am5JdmhkYjB6dks0b0hx
eExYalF3dU9kSDB5S3NSRnNqU2t6U2R3UlNhdVJPTFF6V3Z5MElHVDRLeEI2YnZuOFIyaWlCQU9aTmZC
d1lQTUZKcnE3Qk1zakkxTFQzWFZjQXVlUzFWeFplZktLQXV5MjRwX0RLRGpja2I5RHh4alBFU3dDN0NX
TE0wSnBXVTVSY2xUZ1Y4Q1d5b3RtZ3hfWjRTVGZ0UHhNdG1QVjVzYnhZOEpYcW43TlU1b2t2d3VqYmV1
R3dXNWtleXpQei1UZkZGY0w5XzJrbThPc0ttVFdubi1nUk5uaGpnODRsdUEtYW1xdHk5elNlbmtGaGZC
Q25iZFlJSEwxLUxyOGFDNlU4VV9qVUIxOUlRRG42b2pldXBCT2lpZUlsMFZ5bWhxX0JtaVhLZUh6cHRx
UGtRRzJ6Rk5GdUhlNUtDOTc3WFowNmp1cGlRRlEzT2FDOXh3X3B4SF96YjlDZURLREptcUNOVEdpU3hG
ZlRKSTFCSXNyQjRDcVpORlBjX2hVaF9hZ1hDNHNFT2lIVFVBUGMzVDlYaFktdmlaUk9KWUs1ZkpLOUtP
bmNjWDNHeDBvNmUwTWlxcGsyUmwwa2vYQFkCABZVfxIKXarktVL+QZPgGlQAcj4G7KaMzxxKUfAq61lW
/Wkb+BwCiHhTBKAttHoS2W9Sx0QKM9hSHR8fbkrokJ3qyBPST5LPSuMtYoO0Elc4LjcCcFoySPlWJmfO
CBYLcFJ7aF7zGeUUBgDDectj8dAbosW23+luoj5XgvfYjtxc1bZ6aG0KkLP2kJiY1xZPBQWquewunRXG
XsDv7WRUd+eNawT7P0+pWmg82RMpxYgODXM6+ACpNKbBB6IvVkuc5zr7dw2n1f8EFNDvCyVmoovq0mT/
W3XlZV5np/crZa2XyVV6rcBHHzfGGpW+l2lNhN0jv9A8epXd7bEseq1FetThnfY2zlIRJHSUNoZWl8/a
ZT6H1XLscwp0871fH2CF1PrnjMK8taXnfJF/pT/tk+DUoOhDZMDqPjgVLgjCp/gaWjY5e+2pGXUBkiws
+cdMyF6Hm3OOkEQLnXvxc8+HCNgNay/epA4RpkpCgJMZ3MkAHMyWHV5jQ8M76VyVRjy9iKfjbfD2tP+6
jvWynuOMUdDy9xVBLBj0Q6VXls1WOrOR60nxjTpjuueGhy56pekUHWLGWP2tNELS9FN23eRoAHHBAnDq
KiT+e6SqcuWSLeD8hFkdeCfP/kPGfY5j1CqcpspbBCsNx7O1DDJo+MhSFJD+DtFboNlQg+ZS+s5/OQ8w
2EBZAgDVE87CiGrXqvbr2OIN9hSPEpmsoqqMqCcqbiRyjf5BpSSmjWJavzaoZHv0cCjsiogFOytD9K9B
ify8MmBkcS9vCg4eHmDN1JP82XbDU54xI0WhaAKqJc8w8G1GQptd9G3ALXvNl39jd1fqGF7TjZGpZfok
kg/OWP5+RwdXbCIg2+UGg8BYWUIitSMxVxrfHO69xJhO/cRo/S5ZQ7UKUBvWXoM3fHTg07VGFkFaM9dA
hjM7y4tyyPfFT+lwtr/bGCHSUs0Ta4T+XVm0AcGmwBzXhsVzjjMqXZf/wGhwsxtno2kIsQDZRzb28UcP
kgyqAlRaMcjeIWLck0v5++dQA4acSxuahvu2tRj+YYj/8dskQEP0y9i4YE2ip8GRH5sucqfUVWBoEFOl
5GTFdRTnTofn5SN7iOpV1H+kfxVT0pA0T3LFdUsyYoyvU2Puucljfz6Rp4sWbYYs/qirf93ib/mlGtyq
XtFQvv+eDD9xX3LvDeZf/1gjkz+bQh1NPHtNapc5WPAPirTYIq9IaNRcGjlhf+CVjugFFjdUd8yMEtss
2ufy4ODOVwC4vxIH+VyTUYxHynIH6w6VrvnH3DC6S0EAdCwtQvSb+/HvHFLBXJOys+lUxHRSBrpdi2DM
FXP4Q6kBaaDPrOCGZzUsKS8EsvIyZ22Un/Zks7Z9kr1erkSofQ==

**Comment by ninabreznik** [comment]
pmNhbGdsUlNBLU9BRVAtMjU2YWVkQVFBQmNleHT1Z2tleV9vcHOBZ2VuY3J5cHRja3R5Y1JTQWFueQKr
ckZqbmx4OU10d3NURTdUTE9VYUlEekx6WjhFU0NES2htVVl4WDZQVkJzQmJDRzNBcndSQ20xOTFZbDh3
ZUJub1VVaklZT194Ykh6eHVXS3dkNHBrSnpMakZlN3NIYXQyLUx0REtsNlg1Q2c4NGd4cXd6WHlSWEM3
TEVDNGtpOGdiMVowR243MzNnZmw1R0tVamhJaF91bUoySnRHNi1GQUFCNzlnS3BJNk00aklGUnZXVHZW
V3RkUEJtUl9NRGQ3anJ2UHRnNUlqUG1vMFlqVkkzYTdoeTJSU3VTRWRVYzltS0hCbzlrQ0RSS2pTNWxQ
MHJrY2lUTGJlaEZUWWQteTVxdklWRlVBSkc0YlNld2ZCU3NtZjlnUXpCZHlMQTVPaThOZnp5WG5CNkk3
aUNKNFZQX3hpQkw0b2F2c09jNFNwSFBvOEVtcEt5R0RhbnlXTnVQTUp6SHpTZWk1SmpLbk1xUUdOaUV3
SWFteHpaTGpuT0tPeUs0Y3R6ZnpIcFdqWG0tR1pDV05NZnFKZjloaFhSa0loX3BldldiUjNjNGc0WmNt
ckJfOUp0VHVvUTZZZEdjM3NadFIyNzJpNzMxTDV3YVdIem5nUndNcTMzUVFEcG9BS1pnSi15SU1jQjRv
S293Q0hiekZmR0lIT1Fxdk81U21QNmNCV1BfR1NsRWV2SWs4ZUp1Q3VHUENKa0E5TVRNUkFpNGtoNzM4
dkZ2WXZGQ0VXZmw3b3Ywb0s5WFhjQXFZdF9Yb1RFVmhjRWdiWDRQa3dMdVZYV0FDM1ZhZk1mTEpIOXR1
MTljdkVONWNZcTdrN0RMSjVHdGNOX1lwYXFHZW5ZOUpZcTZjbXBYdUFseVJSUE1FRDdwTTR3X19mM1FS
YTlCaFJjaUdWNzU1Vy1GZ2ozYkQxTzDYQFkCAN0dkDKCdP8ZSSNuH4iwAHEpXH1Ud5YBY9B6g+zEayJz
v1ndYIeM3on+mg3OCqQXjueHeHiW8BwP1ZFxAqVxcyVUySFwXLOHURZzkQdQawfmfgFwhqsEhnbz+7pn
zvGid47N385yqIJHzkITP9YY4/MoETzdoBOb/WKTi9sDM1r5aH4HWvW+pRQNO750ELfYo749ytkhCFbP
SP0fCetQKgLcKvu0eq4eoBxoCR25iM7zx5cGjc2YBJi9btnu9t6oZmvpMpSilGooMEo+nbFxAYizH4ZE
tZrJEUjLptnAypH7Bn9ZwYafG+Ow5fQKtPi336sNHMaMbEU9v43VINzkliPUtyvRo6fx7p+JhE7YwL4E
THdidlAcVLlgYnWlYAd8HRs0/vUUSn/Y1GYjEB6L4zt1fUgYOXcfdPPMCpRV9PqQMMusFxAG216t2538
GTB05hfCVYp1xUitCaZtu+l0LPJq5d0waDp3Dttv2MoMnIGKRXXS+cQjFSNf1gBcrmdjtnN5eZtyCzFR
hPy5QxrEDuv34zHPs7jqVBijkU4v6wzINyCCqpaj3p3IOC3SsZNAAFag4HFkdj5dkwB+xmrmOmikL+K7
VtrU11HfPJarsxVRtWTuEAfw/LAnLfSLDTcZ1LER/yPTmcoa644CWlejgRnIUkFz0zURytGT9RFxsXlo
2EBZAgA/kydOS/9uKFK60IZPX2YK5iwK2tQ1q5wq7Yr+QQlkGweI9JhlXYqb5vpY00NjOWl+l4hkwbnS
LAs3/DU7SIbXBeyAghPgZ6MFVNURLUUIaBsEHLo6ddh8L9yPKDjnMQUK5c9lfhDgrA3SRIv8J2SXeQJa
UQZ3wahiuofhF5nJFYiarWW4koyE4Gmm+LvlA/XdFtDOZDDbHsmDiT2uzTuIriFGoXm1ICqDVTc9sGL4
F3wd51hgMk6K5/nF1+31bOZ4lloYLBM52EyqwDWN4alLWhWpvHjUsGvLnHdmwlo6RSnwVW1s9uk7vxwU
jUeHTcIeeGi+f2D8+wq4Fa2X28a6hvFfbnDXMMpCOiAslN52T9dmINiYqV3G2uKbdcgUrJpt/qdtWk4y
Ovo1Jk4U+EivPH8CDTrViDQ9SFtF9uzBK/qHZARZ0YIot6OrTCaYWXaY3CNCWIC4ezvl5UhHiH6/rnpu
T4k93J9x1qK29q9T87Y0jKgdnyFuX8fRFrTmOYE7WRDM4aGBjWoUti+qchJzKnetmqirl5SafYm9ps6N
t/unswZw32lrZm4782SSJra9C8MNNjw7SlpvVvH+6O0XbLBd7VJs4zFmpwkguM/rmBLB5X3i/O6V32sZ
+Sa9w+sW43dfmR1CHmYwWOxhjO27eSJAmTl9mmVASXi4Ic175w==

**Comment by martinheidegger** [comment]
pmNhbGdsUlNBLU9BRVAtMjU2YWVkQVFBQmNleHT1Z2tleV9vcHOBZ2VuY3J5cHRja3R5Y1JTQWFueQKr
ckZqbmx4OU10d3NURTdUTE9VYUlEekx6WjhFU0NES2htVVl4WDZQVkJzQmJDRzNBcndSQ20xOTFZbDh3
ZUJub1VVaklZT194Ykh6eHVXS3dkNHBrSnpMakZlN3NIYXQyLUx0REtsNlg1Q2c4NGd4cXd6WHlSWEM3
TEVDNGtpOGdiMVowR243MzNnZmw1R0tVamhJaF91bUoySnRHNi1GQUFCNzlnS3BJNk00aklGUnZXVHZW
V3RkUEJtUl9NRGQ3anJ2UHRnNUlqUG1vMFlqVkkzYTdoeTJSU3VTRWRVYzltS0hCbzlrQ0RSS2pTNWxQ
MHJrY2lUTGJlaEZUWWQteTVxdklWRlVBSkc0YlNld2ZCU3NtZjlnUXpCZHlMQTVPaThOZnp5WG5CNkk3
aUNKNFZQX3hpQkw0b2F2c09jNFNwSFBvOEVtcEt5R0RhbnlXTnVQTUp6SHpTZWk1SmpLbk1xUUdOaUV3
SWFteHpaTGpuT0tPeUs0Y3R6ZnpIcFdqWG0tR1pDV05NZnFKZjloaFhSa0loX3BldldiUjNjNGc0WmNt
ckJfOUp0VHVvUTZZZEdjM3NadFIyNzJpNzMxTDV3YVdIem5nUndNcTMzUVFEcG9BS1pnSi15SU1jQjRv
S293Q0hiekZmR0lIT1Fxdk81U21QNmNCV1BfR1NsRWV2SWs4ZUp1Q3VHUENKa0E5TVRNUkFpNGtoNzM4
dkZ2WXZGQ0VXZmw3b3Ywb0s5WFhjQXFZdF9Yb1RFVmhjRWdiWDRQa3dMdVZYV0FDM1ZhZk1mTEpIOXR1
MTljdkVONWNZcTdrN0RMSjVHdGNOX1lwYXFHZW5ZOUpZcTZjbXBYdUFseVJSUE1FRDdwTTR3X19mM1FS
YTlCaFJjaUdWNzU1Vy1GZ2ozYkQxTzDYQFkCADzzi0VCsBLNVFWPrRz1vROIRWSI576PSGAXnbjedDCO
BLLDomcGEwHVgn+h6WJ7lhF6aDP+yUe2kDZnOBPD2OnY9lZvmxGJ3c8wfi8GC2wFMpdmbK6N71+32ZpS
en09A3WfB7k1iVlL/RsnwmovRHEe/CrtHGLoDOXznMpNBdDWetlIGJRnt/FaBjr04Niz6cr596r08mn8
CpFtASOO0ljWiI1lDPXBTM1yezu53BAmKOoOFKwKN7iWcAiVe+FP1xkqFGT5DTXymxsUMVXGCEvtR276
BW9CUaCfe2OfkboYH+P7tbDve/aIxvc2S2GYVbyBL8qZMaJne4/ua7UzLuYZkNRqULTHKHjYgPlruVtv
5cPZU5v4DWLe+Ecy611azwFDPRHUftwQgGLtK3ZywIFtPNrOL2yVgsUc+369N1Y9k8SYsx90P/mwABez
dhvrzZ6LH9YR25BGemXzMTOMmkapgzRtXjFbwoF0QxPFmURpeXZuoqjYqoC1Eg8heMbM+J2JjU3aynE8
MI0wnPfi73H/8lctZgC7aJCJBj4mX8NuNPCqGc3VbGnos9l4t0EEQ3F12szJKhGJ/z5tUk2PkPAHcYzA
/CHPS3X3ak9/4uZeFwxEFISI2Dmei5jMbF/UHai6JkTFpMhpV5yPqUaKyU5O7L0F6eoVSAWUvXT5wBx1
2EBZAgBHgtQdi3ym6hfwIgrxPV7pRD27Zofp6xONsLn0YxK8Mgy189npaO6xUKA/Ox9TFWCJuNfwMhJH
9BeN0w8TuqAAYGwEC8UDj59bczKrrajX7StAmpvDUoKcghp1TjexQpQ/c1n+AMO4mD8s1arw8a0lPLQ7
egAjdj0M3zN48zDCcMCRDUkWDbHkdqwAVAXCEq8ugLKz3WBm4ynYEYxHTDsfiAto/F9iy+YdstDqmfmS
Lw2TMPZwDqv2lcuBGj4xg+mR89XuVLwYX1dFLA16xYMBtbPDTrVcm7B2CeMlt16i6/h9crfpR0/y4ALe
JFhEcJLbo56ZcWUPjgs9LbDPTX8pdfcCVW7Po7rj9uHnDQDqv4EpX5P1CnJuRfox6NQ2M32t5o9hu+2a
s+UBKdfrOKagiW/Wa6eJEqgvuM07jOy0LJGR/s26ZgL6szT8X16PLwXhvotWpaPrDHOW4E4KsiZIxuY2
rRrohwkYWs5Vog6WYbSNTOOIGfO8iBIKGmtEln+n6/78i8FumJVNZ8d9A7MSfqcm7L5rm9o8rH8O5Lpi
rP/pQo423T1zcj56aJGU0k/PAmUANkBoxg5hx/y3RjntjQSaOruaCmIsb2xrLLcARBjMbLbC3BbH771a
vdqmdc35EIHuDYQDOVE7blt5ZKVfJ+Pj+7MbZhyIsiZvsUumOQ==
