### ISSUE TITLE
NPM Organization

### ISSUE THREAD

**Issue by martinheidegger** [dat-ecosystem/organization#5]
Hello Consortium members,

When working on "dat-dns" I was talking with @pfrazee about having access to npm and was wondering if its a good idea to use a npm organization for things that we may want to publish as a group.

In anticipation of this being an accepted/good idea, I preemptively created the `dat-ecosystem` npm organization and invited all but @ninabreznik and @zootella because I couldn't figure out their npm accounts: please let me know what it is if you would like to be invited as well 😅.  _(it can be deleted if someone disagrees about it)_

**Comment by RangerMauve** [comment]
I think it's a good idea.

**Comment by ninabreznik** [comment]
I would personally prefer publishing under our own names and keep Dat
ecosystem as a group for managing relations and share work between
independent projects...
