### ISSUE TITLE
Message to the consortium

### ISSUE THREAD

**Issue by wassx** [dat-ecosystem/organization#67]
Private Message:

pmNhbGdsUlNBLU9BRVAtMjU2YWVkQVFBQmNleHT1Z2tleV9vcHOBZ2VuY3J5cHRja3R5Y1JTQWFueQKr
bGhQbXFzcktrSTE0Q3VRcnhydWhYYUlpaWVlMTl5ejdyZFl3bmxERjQ2MWh0RVhmTVRvcldYM0tQZ1gz
clVaMG1EZnlaam4teXBoa1puUndDRU9aNVRqdFMxU2JndUNlTFg5UU5DQWpkTXVyR0FUUVNZaTZ2Q0t2
alVRZEZveHFrU2xqWEk2TkNEVHpQaVB6Z2NnWngzOHVTZUdlM2R1RDQ3UTBDOUtpdWZXOExFMU1hUG5K
eXQtOE9qYjktWWNOcWw0a2ZIVVA5SWNFLUNodTJTQXFZYlhXZEppN1V0b2VZSGd5LXp5LTYzTXVOaTli
SXNMZEFoZVVtOTRaZmgyMlpDYnlSNlVKQjYtRDJaYUo2Vm9FWGh5MHdGVmlPNHBPaG5pZGE2XzIwaGd3
RWVEY0Myb0N5U3RXZDFDUEloV25wUnpneDItT1EtRWdHclQyUDdKUm9PdEtndEtuRkVHRnBsaURiaUNN
enQtcU5oZ3hDb1J1Z2lDLTdxcTlIQlJpa01BRktzeDMwSnVCcjZWZFZYQ3BEVlpoelVwMGY1WWlPcjNB
bkN2OXZSSDhrMjFDbl9md3BaTGZLMmhlRVYwXzRPNUpkdnNFTmdiaXNhSkpuMHRVZS1oWHFPOXdhQU9X
X1FKNDZiV0hLeERSM190YkozUUxJMHdxWnVNWmF3b1FhY3dtM2ktdGhfS0Jpa0ZOQ280SVhrdWF6WENM
eUdEdWJCeUV1elpULU5KZ1dQSEd6SUNzbjM3UVlhd25vTExHZ2tFVnBqQmd4WWJjalRIMUxScGZtdkFv
YzRnT2hGY1djZjgzWkl2eUFTSlFsOVJCc1NqNDIzSUhsU2dqb0NHajlBUExNVU12RkQyNnd0ZFFTdXRa
NkNJYl8xRlFsVlR4SElRc3hvLTJMYVXYQFkCACvc6MtYNM2bunJ+WqiPCbLracFrTi1KnFI6pBRSmsPl
q4vV+5x5v/WDhKwbVurfhWGJgoraI873Yju05CM6bLn2udA1kVrZsXU+74PJH/I6lA2gy8uctGuKaTgC
PJopQ2IKtPQZtLswoVsTVyQQr1sB7uIdYDAwzVxyM9iYAZxSyhUFNw4RaRokOEqOYusJ1qr2alFcast/
/yzUaGTo+SA5Lg89gkMRlm/mfiRomy1Z65XyLmpXZHgs7FfhUezQSQO0yxpes6GIqs/nyYaGOO2wGgzf
pjOsL52+0ZOUzzh2/NlTtXXYQphXZnasUEq+GOgu1oGEjF01OEDv2KlMLTKCKFNmDblsAJrXyiWQ4UQK
+bQcETbwjaSfKU12ZzUluP8MgHxfsqrTmBXbjNjTWn2jA2hbeC7s9X+uufOiG7SUP1WCo3bSEKPGSq+w
fAU/4/3hxk16PPqzMt+UhbRbZbcU3055YLVhmRttmbKYUmtM8qHIth3VS6RLiuYTeNC8QE4OiInWcxLR
rUjGMgdrjTcST7mhapJN7iV2jZ11GqJE2rAe5fn5RYD0ZonX7EkpOzdYxXVryXkKKoOGZGy8psasYBIN
fBUUAnS1ey3suhLwa1mLArSH4TQuxhcGUYghEoB1RaP5BKn7uLdAqKnC69UuRMialXLWYmWw6bAca3uW
2EBZAgAng3xUMf9iawvXd9Ik9Q0eks8deH7IlfhC/IOLJcGLnlqmQSW1dKt8EXOtPs1XeepHZxL06/re
bfPjCXxSV6x181lT1TZxsMKHBNKcw44YeTl7b8Q5IZDSgvt6ADiVYHNB/YNwY0MS44Q45VlZ0gmKcfDy
AFU40Xt+58g48+m4Ea12b51Eh5vQgkK4KFUNsdTKj1zWrrK8tJFLES2lzuA8nCXYBMYyB/cwZS/J8l1E
1LumGix7fuzKMaUVz3Gj5td38znkoHLDf48BxdNjMp5PIAaP1osjHKkNODATUyJuWiOuRMBaADvr58uO
OvRD8ISSCX2b29me8MfuR9/NhR4od+KDRUuVYHiYN3s2UWiCSJAo8FFUXcpy7em5FbwOVYkZCWFXTPm/
+tlslcYoWJsSWzKJozoRraomkCvNILOKUXqS15+ZtEu0a4Bq9xgrCbSZ6pjCyi1FVGv2w1cVNJafxgBG
SvlWCfnlar065PPmhUAayIt7kuEE1NOJXoIeECQN9EWT1JIuy6Lghy24GbvaYplx0EcwEhVZEfFTRI+B
o+6f208kKzSgqmEEV56heoJEI8FyISo9SlP7worE2wZQ7nP7vflUpW9e5ePjZ+67iCgs5757wRfeE3zy
GoCLmZEIiS+/sQrGCLjuuzueqoOQBCu7pdsdzspO/Vmek0NBiA==

**Comment by serapath** [comment]
Hey thank you, but we undeprecated the packge.
The dat-ecosystem project has a 10+ years history and we will need this name going forward.
I am sorry to inform you that we can't consider your request and hope that you find an alternative name for your project.

Other than that, the form is meant to be used for very confidential requests, such as Code of Conduct violations, but requests like the one made also fit a regular issue or maybe a private message on twitter/discord or any of the social platforms we are supporting :-)

Anyway, I will close the issue now.
